// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcfTvfusInX_lNahHiQGErENgC1DgiS4',
    appId: '1:488297750810:web:bebbb918bc9b4dd9cd8ca3',
    messagingSenderId: '488297750810',
    projectId: 'fb-sfu',
    authDomain: 'fb-sfu.firebaseapp.com',
    storageBucket: 'fb-sfu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoxKZ8sSg2kWvaPjpCV6tnRyMuwwUiKA4',
    appId: '1:488297750810:android:873dfee00b3f601ccd8ca3',
    messagingSenderId: '488297750810',
    projectId: 'fb-sfu',
    storageBucket: 'fb-sfu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLINr8dKEKg0Mc3cRtopH1i-C4NCgbBlY',
    appId: '1:488297750810:ios:3ac9817a5a65778dcd8ca3',
    messagingSenderId: '488297750810',
    projectId: 'fb-sfu',
    storageBucket: 'fb-sfu.appspot.com',
    iosClientId: '488297750810-q90af008h7uk0g94k22vd31vcn3fsqu3.apps.googleusercontent.com',
    iosBundleId: 'com.sfu.project',
  );
}
